apiVersion: v1
kind: Service
metadata:
  name: im
  namespace: or-pro
spec:
  type: NodePort           # 配置为NodePort，外部可以访问
  ports:
    - port: 9403
      targetPort: 9403     # 容器暴露的端口，与Dockerfile暴露端口保持一致
      nodePort: 9403       # NodePort，外部访问的端口
  selector:
    tier: im